version: "3.7"

services:
  mongo:
    image: mongo
    container_name: "recofach-db"
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express:latest
    container_name: "recofach-db-monitoring"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
      - mongo
    ports:
      - 8888:8081

  core:
    container_name: "recofach-core"
    build: ./core-service
    ports:
      - 8080:8080
    expose:
      - 8080
    environment:
      - "SPRING_DATA_MONGODB_HOST=mongo"
      - "SPRING_DATA_MONGODB_DATABASE=core-db"
    depends_on:
      - mongo

  app:
    container_name: "recofach-frontend"
    build:
      context: ./frontend
      args:
        - "api_url=http://localhost"
        - "api_port=8080"
    ports:
      - 3000:3000
    expose:
      - 3000
    depends_on:
      - core
