version: "3.7"

services:
  mongo:
    image: mongo
    container_name: "recofach-db"
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=core-db
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongo-express:
    image: mongo-express:latest
    container_name: "recofach-db-monitoring"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=core-db
      - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_ROOT_USER}
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
    depends_on:
      - mongo
    ports:
      - 8888:8081

  core:
    container_name: "recofach-core"
    build: ./core-service
    ports:
      - 8080:8080
    expose:
      - 8080
    environment:
      - "SPRING_DATA_MONGODB_URI=mongodb://admin:admin@localhost:27017/core-db"
    depends_on:
      - mongo

  app:
    container_name: "recofach-frontend"
    build:
      context: ./frontend
      args:
        - "api_url=http://localhost"
        - "api_port=8080"
    ports:
      - 3000:3000
    expose:
      - 3000
    depends_on:
      - core
